# Generated by Django 5.0.1 on 2025-12-25 00:18

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('worst_player', 'Worst Player'), ('fastest_player', 'Fastest Player'), ('slowest_player', 'Slowest Player'), ('fastest_catch', 'Fastest Catch'), ('slowest_catch', 'Slowest Catch'), ('most_tags_given', 'Most Active Tagger'), ('most_tags_received', 'Most Caught'), ('custom', 'Custom Achievement')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('value', models.CharField(blank=True, help_text='Achievement value (time, count, etc.)', max_length=100)),
                ('icon', models.CharField(default='🏆', max_length=50)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-awarded_at'],
            },
        ),
        migrations.CreateModel(
            name='GameSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_start_date', models.DateTimeField()),
                ('game_end_date', models.DateTimeField()),
                ('tag_points_rank_1', models.IntegerField(default=50, help_text='Points for tagging rank 1 player')),
                ('tag_points_rank_2', models.IntegerField(default=40, help_text='Points for tagging rank 2 player')),
                ('tag_points_rank_3', models.IntegerField(default=30, help_text='Points for tagging rank 3 player')),
                ('tag_points_rank_4', models.IntegerField(default=20, help_text='Points for tagging rank 4 player')),
                ('tag_points_rank_5', models.IntegerField(default=10, help_text='Points for tagging rank 5 player')),
                ('tag_points_rank_other', models.IntegerField(default=5, help_text='Points for tagging rank 6+ player')),
                ('time_penalty_per_hour', models.IntegerField(default=5, help_text='Points deducted per hour of holding tag')),
                ('bonus_untagged_day', models.IntegerField(default=35, help_text='Bonus points for untagged isolated day')),
                ('first_place_prize', models.TextField(default='Hlavná výhra', help_text='Prize description for winner')),
                ('last_place_prize', models.TextField(default='Antikvýhra - Surströmming', help_text='Anti-prize for last place')),
                ('tag_holder_since', models.DateTimeField(blank=True, help_text='When did current holder get the tag', null=True)),
                ('enable_notifications', models.BooleanField(default=True)),
                ('notification_title', models.CharField(default='Nový tag!', max_length=200)),
                ('notification_message_template', models.TextField(default='{tagger} tagol {tagged}!', help_text='Use {tagger} and {tagged} placeholders')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_tag_holder', models.ForeignKey(blank=True, help_text='Player currently holding the tag', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holding_tag', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Game Settings',
                'verbose_name_plural': 'Game Settings',
            },
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('was_tagged', models.BooleanField(default=False)),
                ('tags_given_today', models.IntegerField(default=0)),
                ('tags_received_today', models.IntegerField(default=0)),
                ('points_earned_today', models.IntegerField(default=0)),
                ('time_held_today', models.DurationField(default=datetime.timedelta)),
                ('cumulative_points', models.IntegerField(default=0)),
                ('cumulative_tags_given', models.IntegerField(default=0)),
                ('cumulative_tags_received', models.IntegerField(default=0)),
                ('cumulative_time_held', models.DurationField(default=datetime.timedelta)),
                ('rank', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-cumulative_points'],
                'indexes': [models.Index(fields=['date'], name='game_player_date_4fd720_idx'), models.Index(fields=['-cumulative_points'], name='game_player_cumulat_7671ed_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('points_awarded', models.IntegerField(default=0, help_text='Points awarded to tagger')),
                ('time_penalty', models.IntegerField(default=0, help_text='Penalty to tagged player')),
                ('time_held', models.DurationField(default=datetime.timedelta, help_text='Time tagged player held the tag')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='tags/')),
                ('verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tagged', models.ForeignKey(help_text='Player who was tagged', on_delete=django.db.models.deletion.CASCADE, related_name='tags_received', to=settings.AUTH_USER_MODEL)),
                ('tagger', models.ForeignKey(help_text='Player who made the tag', on_delete=django.db.models.deletion.CASCADE, related_name='tags_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tagged_at'],
                'indexes': [models.Index(fields=['-tagged_at'], name='game_tag_tagged__dff9f8_idx'), models.Index(fields=['tagger'], name='game_tag_tagger__a1ab32_idx'), models.Index(fields=['tagged'], name='game_tag_tagged__74241b_idx')],
            },
        ),
    ]
