# Generated by Django 5.0.1 on 2025-12-25 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_participating',
            field=models.BooleanField(default=True, help_text='Whether the user is actively participating in the game'),
        ),
    ]
